'use client'

import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import { InputProvider } from '@/contexts/inputContext'

const roboto = Roboto({ subsets: ['latin'], weight: ['300', '400', '500', '700'] })

export const metadata: Metadata = {
  title: 'Mama.AI',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={roboto.className}>
      <body className='animate-fade-right animate-once animate-normal bg-black-700 overflow-hidden '>
        <InputProvider>
          {children}
        </InputProvider>
      </body>
    </html>
  )
}
