'use client'

import './globals.css'
import type { Metadata } from 'next'
import { Inconsolata } from 'next/font/google'
import { MantineProvider } from '@mantine/core'

const inconsolata = Inconsolata({ subsets: ['latin'], weight: ['300', '400', '500', '700'] })

export const metadata: Metadata = {
  title: 'Mama.AI',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inconsolata.className}>
      <body className='bg-black-700 '>
        {children}
      </body>
    </html>
  )
}
